Numpy Array Operations

In [ ]:
import numpy as np

arr_2d_unsorted=np.array(
    [[3,1],[1,2],[2,3]]
)

arr_2d_sorted=np.sort(arr_2d_unsorted,axis=1)
print("Sorted 2d array by column",arr_2d_sorted)

In [ ]:
number=np.array([1,2,3,4,5,6,7,8,9,10])
mask=number%2==0
condition_array=np.where(mask,number*4,number*3)
print(condition_array)

In [ ]:
##adding & removing elements
arr=np.array([1,2,3,4,5])
new_arr=np.insert(arr,2,10)
print(new_arr)
new_arr=np.delete(arr,2)
print(new_arr)

In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=np.array([11,12])
stack=np.stack((a,b))
print(np.append(a,b))
print(np.concatenate((a,b)))
print("stack",stack)

print("hstack",hstack)
vstack=np.vstack((stack,c))
print("vstack",vstack)


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

sales_data=np.array(
    [
        [1,150000,180000,200000,300000],
        [2,250000,280000,300000,400000],
        [3,350000,380000,400000,500000],
        [4,450000,480000,500000,600000],
        [5,550000,580000,600000,700000]
    ]
)

print("++++ Zomato sales analysis ++++++++++++++")
print("\n Sales data shape",sales_data.shape)
print("\n Sample data for first 3 rest", sales_data[:3])
print(np.sum(sales_data, axis=1))


yearly_total=np.sum(sales_data[:,1:], axis=1)
print(yearly_total)

##min sale
min_sale=np.min(sales_data[:,1:], axis=1)
print(min_sale)

##max sale
max_sale=np.max(sales_data[:,1:], axis=0)
print(max_sale)

#average sale
average_sale=np.mean(sales_data[:,1:], axis=1)
print(average_sale)

##cumsum
cumulative_sum=np.cumsum(sales_data[:,1:], axis=1)
print(cumulative_sum)

monthly_avg=np.mean(sales_data[:,1:], axis=1)/12
print(monthly_avg)



In [ ]:
vec1=np.array([1,2,3])
vec2=np.array([4,5,6])

print("dot product",np.dot(vec1,vec2))
print("cross product",np.cross(vec1,vec2))

angle=np.arccos(np.dot(vec1,vec2)/(np.linalg.norm(vec1)*np.linalg.norm(vec2)))
print("angle",angle)

In [ ]:

data = np.array([
    [85, 78, 92],
    [56, 65, 60],
    [90, 88, 95],
    [45, 50, 40],
    [70, 75, 80],
    [95, 92, 98],
    [60, 58, 65]
])

print("data shape",data.shape)
print("Average of each row",np.mean(data, axis=1))
print("Overall average",np.mean(data))

In [ ]:
##Top performer
total_marks=np.sum(data, axis=1)
top_student=np.argmax(total_marks)

print("Top student index",top_student)
print("Top student marks",data[top_student])



In [ ]:
##Failed student
failed= np.any(data < 50, axis=1)
print("Failed student index",np.where(failed))
print("Failed student marks",data[np.where(failed)])


In [32]:
top_per_subject=np.argmax(data, axis=0)
print("Top subject index",top_per_subject)


Top subject index [5 5 5]


In [33]:
normalized=(data- np.mean(data))/np.std(data)
print("Normalized data",normalized)

Normalized data [[ 0.67430652  0.27461677  1.07399627]
 [-0.98155102 -0.4676642  -0.75315688]
 [ 0.9597992   0.84560212  1.24529187]
 [-1.60963491 -1.32414223 -1.89512759]
 [-0.18217152  0.10332116  0.38881384]
 [ 1.24529187  1.07399627  1.41658748]
 [-0.75315688 -0.86735395 -0.4676642 ]]


In [34]:
grades=np.where(data < 50, 'F', np.where(data < 60, 'D', np.where(data < 70, 'C', np.where(data < 80, 'B', 'A'))))
print("Grades",grades)

Grades [['A' 'B' 'A']
 ['D' 'C' 'C']
 ['A' 'A' 'A']
 ['F' 'D' 'F']
 ['B' 'B' 'A']
 ['A' 'A' 'A']
 ['C' 'D' 'C']]
